name: Run Python Script

on:
  repository_dispatch:
    types: [run_python_script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Data File
        run: echo '${{ github.event.client_payload.data }}' > data.json

      - name: Exec program
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: ./start.sh
