name: Run Python Script

on:
  workflow_dispatch:
    inputs:
        title:
          description: "Title of the video"
          required: true
          type: string
        link:
          description: "Link to the video"
          required: true
          type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4

      - name: 📝 Create Data File
        run: |
          python3 -c "
          import json, sys
          data = {'title': sys.argv[1], 'link': sys.argv[2]}
          print(json.dumps(data))
          " "${{ github.event.inputs.title }}" "${{ github.event.inputs.link }}" > data.json

      - name: 🔑 Create Google Credentials File
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: echo "$GDRIVE_CREDENTIALS" > auth.json

      - name: 🍪 Setup Cookies
        if: ${{ secrets.COOKIES != '' }}
        env:
          COOKIES_B64: ${{ secrets.COOKIES }}
        run: echo "$COOKIES_B64" | base64 -d > cookies.txt

      - name: ⚙️ Run install
        run: ./install.sh

      - name: 🐍 Run Python Script
        env:
          COOKIES_FILE: cookies.txt
        run: venv/bin/python3 src/app.py
